### ISSUE TITLE
Misspelling - Bulid vs. Build

### ISSUE THREAD

**Issue by drubitsa** [chiprunner1995/SemanticVersion#9]
https://github.com/chiprunner1995/PoshSemanticVersion/blob/7b353ac9e3a951e239e59a725f897e5ca66be4f7/PoshSemanticVersion/PoshSemanticVersion.psm1#L602

**Comment by chiprunner1995** [comment]
Thank you. I've made the fix and it will be in the next release.

**Comment by chiprunner1995** [comment]
Fixed in commit 13fbe4d.
